# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/athenz-user-cert"
  version "0.0.184"

  on_macos do
    on_intel do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.184/athenz-user-cert_0.0.184_darwin_amd64.zip"
      sha256 "70b08b32c93b06b30ce72692e1e01e00df2c3627c423db4ce8b9492d7448305d"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.184/athenz-user-cert_0.0.184_darwin_arm64.zip"
      sha256 "5cbb31c1f6325a3e7a601110f9042ba690e010b627e86551ee3109e56a9b2ed8"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.184/athenz-user-cert_0.0.184_linux_amd64.zip"
        sha256 "c71d232d96ef8218fa3f33d49d38c6da70a6a75b1ef01c6cdafcedbff1304601"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.184/athenz-user-cert_0.0.184_linux_arm64.zip"
        sha256 "2476745f015dfe1042fe6b8ec728f0de649a10de7c5d4cb8a1615daed6f28cc7"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
