# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/athenz-user-cert"
  version "0.0.260"

  on_macos do
    on_intel do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.260/athenz-user-cert_0.0.260_darwin_amd64.zip"
      sha256 "9f188ef9e39f7ca9b169f50d47d3ba71d46609d69ec5f5154b2d95d1baad797d"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.260/athenz-user-cert_0.0.260_darwin_arm64.zip"
      sha256 "d0136c00a639156d9699ace4641b84f5f4419f3c1b0df0dc381d48210d112f55"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.260/athenz-user-cert_0.0.260_linux_amd64.zip"
        sha256 "589ab1875fb07ec3b7822a00061bfef377558cedb6a3e17d3c1d3fc0cee636af"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.260/athenz-user-cert_0.0.260_linux_arm64.zip"
        sha256 "69a54f15ecb0b879290c07e62fb39c9d841c8cdf94a6e90b724a82307dfaaf6b"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
