# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AthenzUserCert < Formula
  desc "CLI to retrieve Athenz-compatible User Certificate"
  homepage "https://github.com/ctyano/athenz-user-cert"
  version "0.0.88"

  on_macos do
    on_intel do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.88/athenz-user-cert_0.0.88_darwin_amd64.zip"
      sha256 "d924db7e6ac78ae86604b11d466576fcce5b21ca7844f8c774dc923336aa9694"

      def install
        bin.install "athenzusercert"
      end
    end
    on_arm do
      url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.88/athenz-user-cert_0.0.88_darwin_arm64.zip"
      sha256 "92bf1e02d70055bee51d61344925b1c80830d1a5ff78d710516549071437cd85"

      def install
        bin.install "athenzusercert"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.88/athenz-user-cert_0.0.88_linux_amd64.zip"
        sha256 "138fc040a6e89cd1cc29590764e8c2c003f98d20b764a82a3b140de6102e6190"

        def install
          bin.install "athenzusercert"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ctyano/athenz-user-cert/releases/download/v0.0.88/athenz-user-cert_0.0.88_linux_arm64.zip"
        sha256 "3d1cec974651d5ae8a81b0a60fe21d69bfa102f2d5c94f15db3e2ac107e47d89"

        def install
          bin.install "athenzusercert"
        end
      end
    end
  end

  test do
    system "#{bin}/athenzusercert version"
  end
end
